### ISSUE TITLE
Zotero.Promise.method() is not equivalent to Bluebird

### ISSUE THREAD

**Issue by dstillman** [zotero/translate#1]
It's not possible to polyfill `isResolved()` on a native promise. It can only be done on a custom-built promise.

In current master:

```javascript
function method(fn) {
	return function() {
		try {
			var val = fn.apply(this, arguments);
			var promise;
			if (val && val.then) {
				promise = val;
			} else {
				promise = Promise.resolve(val);
			}
			if (typeof promise.isResolved === 'undefined') {
				let isResolved = false;
				promise.then(() => isResolved = true);
				promise.isResolved = () => isResolved;
			}
			return promise;
		} catch (e) {
			return Promise.reject(e);
		}
	}
};

// Polyfill version
var foo = method(function () {
    return 'foo';
});
// Bluebird version
var bar = Zotero.Promise.method(function () {
   return 'bar'; 
});

var f = foo();
var b = bar();
return [f.isResolved(), b.isResolved()];
```

Result:

```javascript
[
    "0": false
    "1": true
]
```

I don't know if this affects our use of `method()` in the translation architecture, but this seems a bit dangerous.

**Comment by adomasven** [comment]
> It's not possible to polyfill isResolved() on a native promise. It can only be done on a custom-built promise.

Yes, unfortunately it's not. Then again instant promise resolution from bluebird coroutines does not work either and that's what we rely on in the translation arch and why we need to support this in the first place. The function can be brought to work in-line with what bluebird does though.

Good spot!
