### ISSUE TITLE
Can the "Uncaught (in promise) Error: getTranslators: detection is already running" exception  be caught and handled?

### ISSUE THREAD

**Issue by phil-scholarcy** [zotero/translate#26]
The specific error is here:

https://github.com/zotero/translate/blob/81991533dd3531acb9bfd6bb9457136a0af75f0f/src/translation/translate.js#L1091

I'm finding that this uncaught exception is breaking functionality on some other websites such as Google Calendar and also our own app, Scholarcy Library.

Disabling the Zotero extension solves the problem, but would it be possible to handle this exception in the Zotero code?

**Comment by adomasven** [comment]
Did you try modifying this code or just disabling the Zotero extension? If only the latter, why do you think it's this code that is causing the issue, and not something else in the extension? Generally, see [CONTRIBUTING.md](https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md). If you think that the Zotero Connector is causing bugs on some website, report those bugs to our forums and we will investigate and try to fix them. It is extremely unlikely, that it has anything to do with this line.
