### ISSUE TITLE
Provide an easier interface to `extra`

### ISSUE THREAD

**Issue by AbeJellinek** [zotero/translate#32]
There's way, way too much code in zotero/translators of the form `item.extra = (item.extra ? item.extra + '\n' : '') + 'Key: ' + value;`

Possibilities:

1. Add a function to `Zotero.Utilities.Translate` called `addToExtra`. It would take an item, a key, and a value, and it would update `item.extra` in the same way as the code above.
2. Add a property to sandbox `Zotero.Item` objects called `extraFields`. It would work like [`URL#searchParams`](https://developer.mozilla.org/en-US/docs/Web/API/URL/searchParams): a live-updating map based on the contents of the `extra` field.

(1) is a bit clunky but `ZU.addToExtra(item, 'Key', value)` is still better than the boilerplate we use now. (2) is neater but probably overkill, since translators very rarely need to _read_ from `extra`.

**Comment by adomasven** [comment]
Somebody who has spent more time with translator development (aside from yourself) can say if this is a good idea (seems good to me but what do I know), but if going for (1) I recommend `ZU.setExtra(item, 'key', value)`.

**Comment by adam3smith** [comment]
Yes, definitely would like to have this. I like `setExtra()` -- no opinion on whether that's better as a utility or part of the item prototype.
