### ISSUE TITLE
Console output pollutes terminal

### ISSUE THREAD

**Issue by K20shores** [zotero/translate#38]
In debug.js, there's a console log that streams output which is only relevant to zotero. This is frustrating for people who develop web apps and also have the zotero connector installed.

https://github.com/zotero/translate/blob/8ad44f44c3e4efa6ad75c903c006bfb71d8d58ba/src/debug.js#L86-L87

**Comment by dstillman** [comment]
It's a Chrome bug.

https://github.com/zotero/zotero-connectors/issues/489
