### ISSUE TITLE
Don't proxify URLs in search translators

### ISSUE THREAD

**Issue by dstillman** [zotero/translate#9]
Ever, but specifically when called from other translators

https://github.com/zotero/translators/pull/2771

**Comment by dstillman** [comment]
I don't have access to Springer Link through a proxy, so I can't test this easily, but maybe as simple as only running the below if `this.type == 'web'` and otherwise setting `this._proxy = null`:

https://github.com/zotero/translate/blob/b75bc2550ae2df3bb307e7abf0d3abad96f79c82/src/translation/translate.js#L1768-L1773

@adomasven, there's no reason for anything other than a web translator to even have a proxy, right?

**Comment by adomasven** [comment]
> @adomasven, there's no reason for anything other than a web translator to even have a proxy, right?

The proxy is used to retrieve attachments and unproxify URL fields in the final saved item, so I guess they are not.
